#!/bin/bash

echo "#!/bin/bash
      conda run -n patty python $(pwd)/main.py \$@" > patty

chmod +x ./patty


echo "#!/bin/bash
      conda run -n patty python $(pwd)/main_bv.py \$@" > pattyBV

chmod +x ./pattyBV
